# Generated by Django 5.0.9 on 2024-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('service_type', models.CharField(choices=[('Movies', 'Movies'), ('Flights', 'Flights'), ('Buses', 'Buses'), ('Cable Cars', 'Cable Cars')], max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Service Slug')),
                ('photo', models.ImageField(upload_to='services', verbose_name='Service Photo')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
