# Generated by Django 5.0.9 on 2024-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Service Slug'),
        ),
    ]
