# Generated by Django 5.0.9 on 2024-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Movies', 'Movies'), ('Flights', 'Flights'), ('Buses', 'Buses'), ('Cable Cars', 'Cable Cars')], max_length=50, verbose_name='Service Type'),
        ),
    ]
