[tool.poetry]
name = "digitalbooking"
version = "0.1.0"
description = "Digital ticket booking system."
authors = ["acharyapuru <acharyapuru@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "5.0.9"
django-environ = "^0.11.2"
django-jazzmin = "^3.0.0"
pillow = "^10.4.0"
django-cors-headers = "^4.5.0"
celery = "^5.4.0"
channels = {extras = ["daphne"], version = "^4.1.0"}
channels-redis = "^4.2.0"
djangorestframework = "^3.15.2"
eventlet = "^0.37.0"
django-celery-results = "^2.5.1"
requests = "^2.32.3"
weasyprint = "^63.0"
qrcode = {extras = ["pil"], version = "^8.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
