# Generated by Django 5.0.9 on 2024-10-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Category Slug')),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'verbose_name_plural': 'Movie Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Movie Name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Movie Slug')),
                ('thumbnail', models.ImageField(upload_to='movies', verbose_name='Movie Thumbnail')),
                ('language', models.CharField(max_length=50, verbose_name='Movie Language')),
                ('casts', models.CharField(max_length=255, verbose_name='Movie Casts')),
                ('director', models.CharField(max_length=255, verbose_name='Movie Director')),
                ('duration', models.CharField(max_length=50, verbose_name='Movie Duration')),
                ('release_date', models.DateField(verbose_name='Movie Release Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Movie Description')),
                ('trailer', models.FileField(upload_to='movies/trailers', verbose_name='Movie Trailer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shown', models.BooleanField(default=True, verbose_name='Show Movie')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genre', verbose_name='Movie Genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
