# Generated by Django 5.0.9 on 2024-10-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Theater Name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Theater Slug')),
                ('location', models.CharField(max_length=255, verbose_name='Theater Location')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Theater Phone')),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
            },
        ),
        migrations.CreateModel(
            name='ShowDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='Show Day')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_days', to='movie.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theater')),
            ],
            options={
                'verbose_name': 'Show Day',
                'verbose_name_plural': 'Show Days',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Show Time')),
                ('show_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='movie.showday')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.PositiveIntegerField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.theater')),
            ],
        ),
    ]
