# Generated by Django 5.0.9 on 2024-10-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_theater_showday_showtime_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showday',
            name='day',
            field=models.DateField(verbose_name='Show Day'),
        ),
    ]
