# Generated by Django 5.0.9 on 2024-10-16 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_showday_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'row', 'number')},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.seat')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.showtime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'unique_together': {('show_time', 'seat')},
            },
        ),
    ]
