# Generated by Django 5.0.9 on 2024-10-21 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_seat_options_alter_seat_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'verbose_name': 'Show Time', 'verbose_name_plural': 'Show Times'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.seat', verbose_name='Seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.showtime', verbose_name='Show Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Is Shown'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=1, verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.theater', verbose_name='Theater Name'),
        ),
        migrations.AlterField(
            model_name='showday',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_days', to='movie.movie', verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='showday',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theater', verbose_name='Theater Name'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='show_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='movie.showday', verbose_name='Show Day'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('show_day', 'time')},
        ),
    ]
