# Generated by Django 5.0.9 on 2024-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_showtime_options_alter_booking_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showday',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='Is Trashed'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='Is Trashed'),
        ),
    ]
