# Generated by Django 5.0.9 on 2024-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_showday_is_trashed_showtime_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='booking',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lock Expires At'),
        ),
    ]
