# Generated by Django 5.0.9 on 2024-10-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_booking_locked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Seat Type')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Seat Type',
                'verbose_name_plural': 'Seat Types',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.seattype', verbose_name='Seat Type'),
        ),
    ]
