# Generated by Django 5.0.9 on 2024-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Payment Method')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Payment Method Slug')),
                ('logo', models.ImageField(upload_to='payment_methods', verbose_name='Payment Method Logo')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
    ]
