# Generated by Django 5.0.9 on 2024-10-31 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_seattype_seat_seat_type'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTicketPayment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='Transaction ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Movie')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='Payment Method')),
                ('seats', models.ManyToManyField(to='movie.seat', verbose_name='Seats')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showtime', verbose_name='Show Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Movie Ticket Payment',
                'verbose_name_plural': 'Movie Ticket Payments',
            },
        ),
    ]
