# Generated by Django 5.0.9 on 2024-10-31 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_movieticketpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieticketpayment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
