# Generated by Django 5.0.9 on 2024-10-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_movieticketpayment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieticketpayment',
            name='transaction_id',
        ),
    ]
