# Generated by Django 5.0.9 on 2024-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_movieticketpayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticketpayment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount'),
        ),
    ]
