# Generated by Django 5.0.9 on 2024-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_movieticketpayment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticketpayment',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payable Amount'),
        ),
    ]
