# Generated by Django 5.0.9 on 2024-11-24 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=20, verbose_name='rule type')),
                ('rule_name', models.CharField(max_length=20, verbose_name='rule name')),
                ('params', models.JSONField(verbose_name='params')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=10, verbose_name='type')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='MaxUsesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_uses', models.BigIntegerField(default=0, verbose_name='max uses')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='is infinite')),
                ('uses_per_user', models.IntegerField(default=1, verbose_name='uses per user')),
            ],
        ),
        migrations.CreateModel(
            name='RewardTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('signup', 'Signup'), ('purchase', 'Purchase'), ('referral', 'Referral'), ('other', 'Other')], max_length=20)),
                ('condition', models.JSONField(help_text='JSON object containing the condition parameters such as "minimun_days":0, "minimum_purchase":100$ etc.', verbose_name='params')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='ValidityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedUserRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_users', models.BooleanField(default=False, verbose_name='all users')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=1, help_text='The currency value of the unit point')),
                ('terms_and_conditions', models.ManyToManyField(to='offer.rewardtermsandconditions', verbose_name='terms and conditions')),
            ],
        ),
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=1, help_text='The currency value of the gem')),
                ('terms_and_conditions', models.ManyToManyField(blank=True, to='offer.rewardtermsandconditions', verbose_name='terms and conditions')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.alloweduserrule', verbose_name='allowed user rule')),
                ('custom_rules', models.ManyToManyField(blank=True, to='offer.customrule', verbose_name='custom rules')),
                ('max_uses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.maxusesrule', verbose_name='max uses rule')),
                ('validity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.validityrule', verbose_name='validity rule')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('times_used', models.IntegerField(default=0, verbose_name='times used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.discount', verbose_name='discount')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.ruleset', verbose_name='rule set')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='times used')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.coupon', verbose_name='coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRewardWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the reward object')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('earned_from', models.CharField(max_length=100, verbose_name='earned from')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='earned at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('content_type', models.ForeignKey(help_text='The type of the reward object', limit_choices_to={'model__in': ['gems', 'points']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
