# Generated by Django 5.0.9 on 2024-11-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrewardwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='user'),
        ),
    ]
