# Generated by Django 5.0.9 on 2024-11-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_userrewardwallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=100, verbose_name='issuer')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='promo code')),
                ('redemption_count', models.IntegerField(default=0, verbose_name='redemption count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('description', models.TextField(verbose_name='description')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.ruleset', verbose_name='conditions')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.discount', verbose_name='discount')),
            ],
        ),
    ]
