# Generated by Django 5.0.9 on 2024-11-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('offer', '0003_promocode'),
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('redeem', 'Redeem')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('entity_content_type', models.ForeignKey(limit_choices_to={'model_in': ['gems', 'points', 'coupon', 'promocode']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='user.userprofile', verbose_name='user')),
            ],
        ),
    ]
