# Generated by Django 5.0.9 on 2024-11-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('offer', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entity_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['gems', 'points', 'coupon', 'promocode']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
